**Intro to Tensors**

In [1]:
print("hello world")

hello world


First, import the PyTorch libraries (import numpy too):

In [2]:
import torch
import torchvision
import numpy as np

A **tensor** is just an *n*-dimensional matrix.

Create a 5x4 tensor of floats, random between 0 and 1:

In [4]:
x = torch.rand(5, 4)
print(x)

tensor([[0.6303, 0.5674, 0.2267, 0.5775],
        [0.1288, 0.4479, 0.9146, 0.2000],
        [0.1621, 0.1673, 0.1504, 0.2996],
        [0.8913, 0.3695, 0.5244, 0.6637],
        [0.7431, 0.8167, 0.5401, 0.3060]])


Create a 5x3 tensor of longs, all initialized to 0:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Create a tensor from a Python list:

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor that has the same dimensions as some other tensor, but different values:

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# randn is normal distribution
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2190,  0.0373,  0.2623],
        [ 0.3182, -0.1266, -0.2133],
        [-1.3340,  1.2166,  0.0900],
        [ 0.5953,  1.2982, -0.3869],
        [-1.3906,  0.9170,  0.2186]])


In [8]:
print(x.size())
print("x has size " + str(x.size()[0]) + " x " + str(x.size()[1]))

torch.Size([5, 3])
x has size 5 x 3


Simple arithmetic:

In [9]:
y = torch.rand(5,3)
print(x + y)

tensor([[-0.8550,  0.1584,  0.7597],
        [ 0.9982, -0.1051,  0.2795],
        [-1.1224,  1.6430,  0.9846],
        [ 1.0819,  1.6434, -0.2927],
        [-1.2152,  1.3199,  0.8034]])


All the conventional NumPy indexing works for PyToch tensors:

In [10]:
print(x)
print("the second column of x is:")
print(x[:, 1])

tensor([[-1.2190,  0.0373,  0.2623],
        [ 0.3182, -0.1266, -0.2133],
        [-1.3340,  1.2166,  0.0900],
        [ 0.5953,  1.2982, -0.3869],
        [-1.3906,  0.9170,  0.2186]])
the second column of x is:
tensor([ 0.0373, -0.1266,  1.2166,  1.2982,  0.9170])


Reshaping tensors:

In [9]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8)
print(z)

tensor([[ 0.2331, -1.9076, -1.9731,  0.6571],
        [-1.0665, -0.7399,  1.4728,  0.9339],
        [ 0.9694, -0.2033, -0.1341, -0.0373],
        [-0.3467, -1.2220,  0.3748, -1.5152]])
tensor([ 0.2331, -1.9076, -1.9731,  0.6571, -1.0665, -0.7399,  1.4728,  0.9339,
         0.9694, -0.2033, -0.1341, -0.0373, -0.3467, -1.2220,  0.3748, -1.5152])
tensor([[ 0.2331, -1.9076, -1.9731,  0.6571, -1.0665, -0.7399,  1.4728,  0.9339],
        [ 0.9694, -0.2033, -0.1341, -0.0373, -0.3467, -1.2220,  0.3748, -1.5152]])


Converting between NumPy arrays and PyTorch tensors:

In [10]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [11]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


**GPU Memory using CUDA**

Any tensor can be easily moved to/from GPU memory.

First, check if CUDA is available on this machine (need to install it first):

In [11]:
print(torch.cuda.is_available())

True


Example operations between GPU and CPU:

In [15]:
device = torch.device("cuda")       # (also possible to handle multiple GPUs)
x = torch.ones(3, 3)                # default: CPU
y = torch.ones(3, 3, device=device) # directly create tensor on GPU
x = x.to(device)                    # need to move x to GPU before adding to y
z = x + y
print("z on GPU:")
print(z)                            # result is on GPU too
print("z on CPU:")
print(z.to("cpu"))                  # copy it back to CPU


z on GPU:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')
z on CPU:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


**Autograd: Automatic Differentiation**

Tensors have an attribute `.requires_grad`. If you set it to `True`, then all operations on it will be tracked.
After finishing computation, call `.backward()`, and all the gradients will be computed automatically.

In [24]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:

In [25]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


Notice the `grad_fn` attribute:

In [26]:
print(y.grad_fn)

In [27]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


Now do backprop...

In [28]:
out.backward() # computes gradients for all variables in the computation graph

In [30]:
print("d(out) / dx = ", x.grad)

d(out) / dx =  tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


We can step backward through the list of functions that were called when computing `out`:

In [48]:
fn = out.grad_fn
while True:
    print(fn)
    if len(fn.next_functions) == 0:
        break
    fn = fn.next_functions[0][0]